```{r}
## libraries
library(tidyverse)
```

```{r}
monty_hall <- function() {
  ## randomly place prize behind one door and name doors 
  doors <- sample(c(1, 0, 0), 3, replace = FALSE)
  names(doors) <- c(1, 2, 3)
  ## randomly generate participant's selection
  door_part <- sample(1:3, 1)
  ## obtain remaining doors excluding participant's selection
  doors_remain <- doors[-door_part]
  ## if both of remaining doors don't have a prize, randomly select
  ## one of the two, if only one doesn't have prize, select that door 
  door_host <- if(doors_remain %>% max == 0) {
    sample(doors_remain, 1) %>% names %>% as.integer
  } else {
    which(doors_remain == 0) %>% names %>% as.integer
  }
  ## obtain result if participant does/doesn't switch doors
  results <- c(switch = doors_remain[names(doors_remain) != door_host] %>% as.integer,
               remain = doors[door_part] %>% as.integer)
  return(results) 
}
```

```{r}
## generate 1,000 simulations
results <- replicate(n = 1000, monty_hall()) %>% t %>% 
  data.frame %>% 
  rownames_to_column(var = "sim_no") %>% 
  mutate(sim_no = as.integer(sim_no),
         switch_sum = cumsum(switch),
         remain_sum = cumsum(remain))
```

```{r}
## plot the cumulative number of wins under various strategies
results %>% 
  select(sim_no, Remain = remain_sum, Switch = switch_sum) %>% 
  gather(key = "cat", value = "val", -sim_no) %>% 
  mutate(cat = as.factor(cat)) %>% 
  ggplot(aes(x = sim_no, y = val, color = cat)) +
  geom_line() +
  labs(title = "Why You Should Always Switch Doors in the Monty Hall Problem",
       subtitle = "Cumulative Wins Over Repeated Simulations with Each Strategy",
       x = "Number of Simulations", 
       y = "Number of Wins",
       color = "Strategy") +
  theme(legend.position = "bottom",
        plot.title = element_text(face = "bold"))
```

```{r}
## plot the winning percentage under various strategies
results %>% 
  summarise(switch = mean(switch),
            remain = mean(remain)) %>% 
  gather %>% 
  ggplot(aes(x = key, y = value * 100)) +
  geom_histogram(stat = "identity") +
  labs(title = "Winning Percentage Under Various Monty Hall Strategies",
       x = "Strategy",
       y = "Winning Percent")
```
